title: 'Jamming'
site-description: >
  блог про альпінізм, біг та подорожі
#email: your-email@domain.com

#description: >
#  блог про альпінізм, біг та подорожі

# stuff before 
baseurl: ""

url: "http://jamming.com.ua" # the base hostname & protocol for your site, e.g. http://example.com

#email_username: your-email@domain.com #Your email address
twitter_username:  ribtoks

copyright_name: Jamming #Copyright

excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
kramdown:
  input: GFM

destination: _site

paginate: 5 #Total Number of Post in each Page

permalink: /:year/:title
# :output_ext

gems: [jekyll-paginate, jekyll-feed, jekyll-seo-tag]

# Exclude our ruby stuff
exclude: [.bundle, bin, vendor, Gemfile, Gemfile.lock, Rakefile, s3_website.yml, .last_optimized]
