title: 'Jamming'
site-description: біг про альпінізм, біг та подорожі
#email: your-email@domain.com

description: >
  біг про альпінізм, біг та подорожі

url: "" # the base hostname & protocol for your site, e.g. http://example.com

#email_username: your-email@domain.com #Your email address
twitter_username:  ribtoks

your_name: 'Taras Kushnir' #Your Name for About
about_yourself: "" # Brief description about yourself

copyright_name: Jamming #Copyright 

# Build settings
markdown: kramdown
kramdown:
  input: GFM

destination: _site

paginate: 5 #Total Number of Post in each Page

gems: [jekyll-paginate, jekyll-feed]

exclude:
  - Gemfile
  - Gemfile.lock
